TracerCafe/Models/ErrorViewModel.cs
using System;

namespace TracerCafe.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

TracerCafe/Controllers/BaseController.cs
using AutoMapper;
using Microsoft.AspNetCore.Mvc;

namespace TracerCafe.Controllers
{
    public abstract class BaseController : Controller
    {
        protected readonly IMapper _mapper;

        public BaseController(IMapper mapper)
        {
            _mapper = mapper;
        }       
    }
}

TracerCafe/Controllers/CustomerController.cs
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using TracerCafe.Data.DTO;
using TracerCafe.Data.Entities;
using TracerCafe.Data.Model;
using TracerCafe.Data.Model.Customer;
using TracerCafe.Services.Customer;

namespace TracerCafe.Controllers
{
    public class CustomerController : BaseController
    {
        private readonly ICustomerService _customerservice;

        public CustomerController(ICustomerService customerService, IMapper mapper) : base(mapper)
        {
            _customerservice = customerService;
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public async Task<PartialViewResult> SearchByFilter(SearchCustomerFilter searchcustomerfilter)
        {
                var totalRow = 0;
                var totalPage = 0;

                var customers =await _customerservice.SearchByFilter(searchcustomerfilter);
                if (customers.Any())
                {
                    totalRow = await _customerservice.CountCustomer(searchcustomerfilter);
                    totalPage = (int)Math.Ceiling((float)totalRow / searchcustomerfilter.Top);
                }

                ViewBag.TotalRow = totalRow;
                ViewBag.TotalPage = totalPage;
                ViewBag.Page = searchcustomerfilter.Page;

                var data =  _mapper.Map<List<CustomerDto>>(customers);
                return PartialView("_PartialListCustomer", data);       
        }

        [HttpPost]
        public async Task<IActionResult> Insert(CustomerDto customerDto)
        {
            var err = new ErrorObject(Error.SUCCESS);
            if (ModelState.IsValid)
            {
                var customer = _mapper.Map<Customer>(customerDto);
                err = await _customerservice.CreateCustomer(customer);
            }
            else
            {
                var message = string.Join(" | ", ModelState.Values
                                        .SelectMany(v => v.Errors)
                                        .Select(e => e.ErrorMessage)
                                        );
                err.Failed(message);

            }
            return Json(err);
        }

        [HttpPut]
        public async Task<IActionResult> Update(CustomerDto customerDto)
        {
            var err = new ErrorObject(Error.SUCCESS);
            if (ModelState.IsValid)
            {
                var customer = _mapper.Map<Customer>(customerDto);
                err = await _customerservice.UpdateCustomer(customer);
            }
            else
            {
                var message = string.Join(" | ", ModelState.Values
                                        .SelectMany(v => v.Errors)
                                        .Select(e => e.ErrorMessage)
                                        );
                err.Failed(message);

            }
            return Json(err);
        }

        [HttpDelete]
        public async Task<IActionResult> Delete(Guid Id)
        {
            return Json(await _customerservice.DeleteCustomer(Id));
        }
    }
}

TracerCafe/Views/Customer/Index.cshtml
@{
    ViewBag.Title = "Manage Customer";
}

<div class="table-responsive m-t-40">
    <div id="config-table_wrapper" class="dataTables_wrapper container-fluid dt-bootstrap4 no-footer">

        <div class="row" style="margin-bottom:20px;">
            <div class="col-sm-12 col-md-6">
                <div class="input-group ">
                    <input type="text" class="form-control" placeholder="Search by: FirstName, SurName, PostCode, Phone" name="Keyword" id="Keyword">
                    <div class="input-group-append ">
                        <button onclick="getListCustomer(1)" id="SearchKeyword" type="button" class="btn waves-effect waves-light btn-primary" data-toggle="tooltip" title="">
                            <span class="fas fa-search"></span>
                        </button>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-12 col-md-10"></div>
            <div class="col-sm-12 col-md-2">
                <button style="float:right" id="btnCreate" class="btn btn-success" data-toggle="modal" data-target="#modalCustomer">Create</button>
            </div>

        </div>
        <br />
        <div id="content">

        </div>
        @await Html.PartialAsync("_PartialModalCustomer")    
        @await Html.PartialAsync("_PartialModalConfirm")
    </div>
</div>


<script>
 

    function getListCustomer(page) {

        $.ajax({
            url: "/Customer/SearchByFilter",
            type: "POST",
            data: {
                KeyWord: $("#Keyword").val() ?? "",
                Page: page
            },
            dataType: "html",
            success: (function (result) {
                $("#content").html(result);
            })
        })
    }

    $(document).ready(function () {
      

        $("#formCustomer").validate({
            rule: {
                "Telephone": {
                    phoneUK: true
                }
            }
        })

        $('#Telephone').rules('add', {
            phoneUK: true
          
        });

        getListCustomer(1);

        $("#btnCreate").click(function () {
            $("#myModalLabel").text("Create New Customer");
            $("#formCustomer input").val("");
        })

        $("#saveBtn").click(function () {
         
            if ($("#formCustomer").valid()) {
                var data =
                {
                    Id: $("#Id").val(),
                    Title: $("#Title").val(),
                    FirstName: $("#FirstName").val(),
                    Surname: $("#Surname").val(),
                    Address1: $("#Address1").val(),
                    Address2: $("#Address2").val(),
                    Address3: $("#Address3").val(),
                    Address4: $("#Address4").val(),
                    Age: $("#Age").val(),
                    PostCode: $("#PostCode").val(),
                    Telephone: $("#Telephone").val()
                }

                if (data.Id) {
                    $.ajax({
                        type: "PUT",
                        url: "/Customer/Update",
                        data: data,
                        success: function (data) {
                            if (data.code == 0) {
                                toastr.success("Update customer success!");
                                $("#modalCustomer").modal("hide");
                                getListCustomer(1);
                            }
                            else {
                                toastr.error(data.message);
                            }
                        }

                    });
                }
                else {
                    $.ajax({
                        type: "POST",
                        url: "/Customer/Insert",
                        data: data,
                        success: function (data) {
                            if (data.code == 0) {
                                toastr.success("Create customer success!");
                                $("#modalCustomer").modal("hide");
                                getListCustomer(1);
                            }
                            else {
                                toastr.error(data.message);
                            }
                        }

                    });
                }

            }
        })

        $('#Keyword').keypress(function (event) {
            var keycode = (event.keyCode ? event.keyCode : event.which);
            if (keycode == '13') {
                getListCustomer(1);
            }
        });

        $("#btnConfirmDelete").click(function () {
            $.ajax({
                type: "DELETE",
                url: "/Customer/Delete/" + $("#IdCustomerDelete").val(),
                success: (function (data) {
                    if (data.code == 0) {
                        toastr.success("Delete customer success!");
                        $("#modalConfirm").modal("hide");
                    }
                    else {
                        toastr.error(data.message);
                    }
                    getListCustomer(1);
                }),
                error: function (response) {
                    toastr.error("Delete customer failed!");
                }
            })
        })
    });

</script>

TracerCafe/Views/Customer/_PartialListCustomer.cshtml
@model List<TracerCafe.Data.DTO.CustomerDto>;
@{
    var page = ViewBag.Page;
}
@if (Model.Any())
{

    <div class="row">
        <div class="col-sm-12 col-md-12">
            <table id="myTable" class="display nowrap table table-hover table-striped table-bordered" cellspacing="0">
                <thead>
                    <tr>
                        <th>No</th>
                        <th>Title</th>
                        <th>FirstName</th>
                        <th>SurName</th>
                        <th>Address1</th>
                        <th>Address2</th>
                        <th>Address3</th>
                        <th>Address4</th>
                        <th>PostCode</th>
                        <th>Telephone</th>
                        <th>Age</th>
                    </tr>
                </thead>
                <tbody>
                    @for (int i = 0; i < Model.Count; i++)
                    {

                        var item = Model[i];
                        var no = i + 1 + (page - 1) * 5;
                    <tr>
                        <td class="Id" hidden>@item.Id</td>
                        <td>@no</td>
                        <td class="Title">@item.Title</td>
                        <td class="FirstName">@item.FirstName</td>
                        <td class="Surname">@item.Surname</td>
                        <td class="Address1">@item.Address1</td>
                        <td class="Address2">@item.Address2</td>
                        <td class="Address3">@item.Address3</td>
                        <td class="Address4">@item.Address4</td>
                        <td class="PostCode">@item.PostCode</td>
                        <td class="Telephone">@item.Telephone</td>
                        <td class="Age">@item.Age</td>
                        <td class="modal-footer">
                            <button id="editBtn" class="btn waves-effect waves-light btn-outline-success" type="button" data-toggle="modal" data-target="#modalCustomer"><i class="fa fa-edit"></i></button>
                            <button id="deleteBtn" class="btn waves-effect waves-light btn-outline-danger" type="button" data-toggle="modal" data-target="#modalConfirm"><i class="fa fa-trash"></i></button>

                        </td>
                    </tr>
                    }
                </tbody>

            </table>
        </div>

    </div>
    @await Html.PartialAsync("_PartialPaging", new { CallBackName = "getListCustomer", Page = ViewBag.Page, TotalPage = ViewBag.TotalPage, TotalRow = ViewBag.TotalRow })


}

<script>

    $("#myTable").on('click', '#editBtn', function () {
        $("#myModalLabel").text("Edit Customer");
        var currentRow = $(this).closest("tr");
        var Id = currentRow.find(".Id").text();
        var Title = currentRow.find(".Title").text();
        var FirstName = currentRow.find(".FirstName").text();
        var Surname = currentRow.find(".Surname").text();
        var Address1 = currentRow.find(".Address1").text();
        var Address2 = currentRow.find(".Address2").text();
        var Address3 = currentRow.find(".Address3").text();
        var Address4 = currentRow.find(".Address4").text();
        var PostCode = currentRow.find(".PostCode").text();
        var Telephone = currentRow.find(".Telephone").text();
        var Age = currentRow.find(".Age").text();
        
        $("#Id").val(Id);
        $("#Title").val(Title);
        $("#FirstName").val(FirstName);
        $("#Surname").val(Surname);
        $("#Address1").val(Address1);
        $("#Address2").val(Address2);
        $("#Address3").val(Address3);
        $("#Address4").val(Address4);
        $("#PostCode").val(PostCode);
        $("#Telephone").val(Telephone);
        $("#Age").val(Age);
    });

    $("#myTable").on('click', '#deleteBtn', function () {
        var currentRow = $(this).closest("tr");
        var Id = currentRow.find(".Id").text();
        $("#IdCustomerDelete").val(Id);
    });

</script>

TracerCafe/Views/Customer/_PartialModalConfirm.cshtml
<!-- Modal -->
<div class="modal fade" id="modalConfirm" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content"> 
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Delete</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                <input type="text" id="IdCustomerDelete" hidden/>
            </div>
            <div class="modal-body">
                Are you sure you want to delete this customer?
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                <button type="button" class="btn btn-danger" id="btnConfirmDelete">Delete</button>
            </div>
        </div>
    </div>
</div>

TracerCafe/Views/Customer/_PartialModalCustomer.cshtml
<div id="modalCustomer" class="modal fade in" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title" id="myModalLabel">Create New Customer</h4>
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
            </div>
            <div class="modal-body">
                <form id="formCustomer" class="form-horizontal">
                    <div class="form-group">
                        <div class="col-md-12 mb-3" style="display:none">
                            <input type="text" id="Id" class="form-control">
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-md-12"> Title </label>
                        <div class="col-md-12">
                            <input type="text" class="form-control" id="Title" name="Title" placeholder="Title" required>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-md-12"> FirstName </label>
                        <div class="col-md-12">
                            <input type="text" class="form-control" id="FirstName" name="FirstName" placeholder="FirstName" required>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-md-12"> Surname </label>
                        <div class="col-md-12">
                            <input type="text" class="form-control" id="Surname" name="Surname" placeholder="Surname" required>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-md-12"> Address1 </label>
                        <div class="col-md-12">
                            <input type="text" class="form-control" id="Address1" name="Address1" placeholder="Address1" required>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-md-12"> Address2 </label>
                        <div class="col-md-12">
                            <input type="text" class="form-control" id="Address2" name="Address2" placeholder="Address2">
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-md-12"> Address3 </label>
                        <div class="col-md-12">
                            <input type="text" class="form-control" id="Address3" name="Address3" placeholder="Address3">
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-md-12"> Address4 </label>
                        <div class="col-md-12">
                            <input type="text" class="form-control" id="Address4" name="Address4" placeholder="Address4">
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-md-12"> PostCode </label>
                        <div class="col-md-12">
                            <input type="text" class="form-control" id="PostCode" name="PostCode" placeholder="PostCode" required>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-md-12"> Telephone </label>
                        <div class="col-md-12">
                            <input type="tel" class="form-control" id="Telephone" name="Telephone" placeholder="Telephone" required>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-md-12"> Age </label>
                        <div class="col-md-12">
                            <input type="number" class="form-control" id="Age" name="Age" placeholder="Age" required>
                        </div>
                    </div>

                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default waves-effect" data-dismiss="modal">Cancel</button>
                <button type="submit" class="btn btn-info waves-effect" id="saveBtn">Save</button>
            </div>
        </div>
        <!-- /.modal-content -->
    </div>
    <!-- /.modal-dialog -->
</div>

TracerCafe/Views/Customer/_PartialPaging.cshtml
@{
    int totalRow = Model.TotalRow;
    int totalPage = Model.TotalPage;
    int page = Model.Page;
    var callbackName = Model.CallBackName;
}

<style>
    .page-link {
        cursor: pointer
    }

    .noHover {
        pointer-events: none;
    }
</style>

<div class="row">
    <div class="col-sm-12 col-md-5">
        <div class="dataTables_info" id="myTable_info" role="status" aria-live="polite">
           
        </div>
    </div>
    <div class="col-sm-12 col-md-7">
        <div class="dataTables_paginate paging_simple_numbers" id="myTable_paginate" style=" float: right;">
            <ul class="pagination">
                <li class="paginate_button page-item @(page == 1 ? "previous disabled noHover" : "" )" id="config-table_previous">
                    <a aria-controls="config-table" data-dt-idx="@(1)" tabindex="0" class="page-link"> << </a>
                </li>
                <li class="paginate_button page-item @(page == 1 ? "previous disabled noHover" : "" )" id="config-table_previous">
                    <a aria-controls="config-table" data-dt-idx="@(page-1)" tabindex="0" class="page-link"> Previous </a>
                </li>
                @{ int dem = 1;
                    for (int i = page - 3; i <= totalPage; i++)
                    {
                        if (i > 0 && dem <= 6)
                        {
                            <li class="paginate_button page-item @(page == i ? " active" : "" )">
                                <a aria-controls="config-table" data-dt-idx="@i" tabindex="0" class="page-link"> @(i) </a>
                            </li>
                            dem++;
                        }
                    }
                }
                <li class="paginate_button page-item next @(page == totalPage ? "disabled noHover" : "" )" id="config-table_next">
                    <a aria-controls="config-table" data-dt-idx="@(page+1)" tabindex="0" class="page-link"> Next </a>
                </li>
                <li class="paginate_button page-item next @(page == totalPage ? "disabled noHover" : "" )" id="config-table_next">
                    <a aria-controls="config-table" data-dt-idx="@(totalPage)" tabindex="0" class="page-link"> >> </a>
                </li>
            </ul>
        </div>
    </div>
</div>

<script>

    $(".page-link").on("click", function () {
        page = $(this).attr("data-dt-idx");
        window["@callbackName"](page);
    });

</script>

TracerCafe/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - TracerCafe</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css" integrity="sha512-1ycn6IcaQQ40/MKBW2W4Rhis/DbILU74C1vSrLJxCq57o941Ym01SwNsOMqvEBFlcgUa6xLiPY/NS5R+E6ztJQ==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.min.css" integrity="sha512-vKMx8UnXk60zUwyUnUPM3HbQo8QfmNx7+ltw8Pm5zLusl1XIfwcxo8DbWCqMGKaWeNxWA8yrx5v3SaVpMvR3CA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="https://jqueryvalidation.org/files/demo/site-demos.css">
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://code.jquery.com/jquery-1.11.1.min.js"></script>

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Customer" asp-action="Index">TracerCafe</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Customer" asp-action="Index">Customers</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - TracerCafe - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://cdn.jsdelivr.net/jquery.validation/1.16.0/jquery.validate.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/js/all.min.js" integrity="sha512-Tn2m0TIpgVyTzzvmxLNuqbSJH3JP8jm+Cy3hvHrW7ndTDcJ1w5mBiksqDBb8GpE2ksktFvDB/ykZ0mDpsZj20w==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js" integrity="sha512-VEd+nq25CkR676O+pLBnDW09R7VQX9Mdiij052gVCp5yVH3jGtH70Ho/UUv4mJDsEdTvqRCFZg0NKGiojGnUCw==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script>

    </script>
    @RenderSection("Scripts", required: false)
</body>
</html>